spring.application.name=cable-control
server.port=9004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.zatichka1=
app.upload.zatichka2=